"""add_thinking_content_to_message

Revision ID: 03630403f8c2
Revises: 70ee7fb4d40b
Create Date: 2026-01-04 15:46:02.555769

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "03630403f8c2"
down_revision: Union[str, Sequence[str], None] = "70ee7fb4d40b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("message", sa.Column("thinking_content", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("message", "thinking_content")
    # ### end Alembic commands ###
