"""add google_search_enabled

Revision ID: 06220fc6f1ff
Revises: 69dab3a4473b
Create Date: 2025-12-13 20:05:11.895352

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "06220fc6f1ff"
down_revision: Union[str, Sequence[str], None] = "69dab3a4473b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("session", sa.Column("google_search_enabled", sa.Boolean(), nullable=False, server_default="false"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("session", "google_search_enabled")
    # ### end Alembic commands ###
