"""add smithery cache

Revision ID: 0a40031876f0
Revises: c3ccad954d9b
Create Date: 2025-11-12 21:48:21.441008

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "0a40031876f0"
down_revision: Union[str, Sequence[str], None] = "c3ccad954d9b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "smitheryserverscache",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("params", sa.JSON(), nullable=True),
        sa.Column("data", sa.JSON(), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("hits", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_smitheryserverscache_created_at"), "smitheryserverscache", ["created_at"], unique=False)
    op.create_index(op.f("ix_smitheryserverscache_expires_at"), "smitheryserverscache", ["expires_at"], unique=False)
    op.create_index(op.f("ix_smitheryserverscache_key"), "smitheryserverscache", ["key"], unique=True)
    op.create_index(op.f("ix_smitheryserverscache_updated_at"), "smitheryserverscache", ["updated_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_smitheryserverscache_updated_at"), table_name="smitheryserverscache")
    op.drop_index(op.f("ix_smitheryserverscache_key"), table_name="smitheryserverscache")
    op.drop_index(op.f("ix_smitheryserverscache_expires_at"), table_name="smitheryserverscache")
    op.drop_index(op.f("ix_smitheryserverscache_created_at"), table_name="smitheryserverscache")
    op.drop_table("smitheryserverscache")
    # ### end Alembic commands ###
