"""add session spatial_layout

Revision ID: 16fcd09524ba
Revises: c712246c7034
Create Date: 2026-01-14 23:53:36.058092

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "16fcd09524ba"
down_revision: Union[str, Sequence[str], None] = "c712246c7034"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("session", sa.Column("spatial_layout", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("session", "spatial_layout")
    # ### end Alembic commands ###
