"""remove_unique_constraint_from_tool_name

Revision ID: 25b4116e5c65
Revises: f2a66d835d66
Create Date: 2025-10-24 01:24:49.673937

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "25b4116e5c65"
down_revision: Union[str, Sequence[str], None] = "f2a66d835d66"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tool_name"), table_name="tool")
    op.create_index(op.f("ix_tool_name"), "tool", ["name"], unique=False)
    op.create_unique_constraint("uq_user_tool_name", "tool", ["user_id", "name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_user_tool_name", "tool", type_="unique")
    op.drop_index(op.f("ix_tool_name"), table_name="tool")
    op.create_index(op.f("ix_tool_name"), "tool", ["name"], unique=True)
    # ### end Alembic commands ###
