"""add file

Revision ID: 2f7e4f948ed0
Revises: 8f78abb0fa0c
Create Date: 2025-12-12 20:23:25.285022

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "2f7e4f948ed0"
down_revision: Union[str, Sequence[str], None] = "8f78abb0fa0c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "file",
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("storage_key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("original_filename", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("content_type", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column("file_size", sa.Integer(), nullable=False),
        sa.Column("scope", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column("category", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column("file_hash", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
        sa.Column("metainfo", sa.JSON(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("message_id", sa.Uuid(), nullable=True),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_file_category"), "file", ["category"], unique=False)
    op.create_index(op.f("ix_file_id"), "file", ["id"], unique=False)
    op.create_index(op.f("ix_file_is_deleted"), "file", ["is_deleted"], unique=False)
    op.create_index(op.f("ix_file_message_id"), "file", ["message_id"], unique=False)
    op.create_index(op.f("ix_file_scope"), "file", ["scope"], unique=False)
    op.create_index(op.f("ix_file_status"), "file", ["status"], unique=False)
    op.create_index(op.f("ix_file_storage_key"), "file", ["storage_key"], unique=True)
    op.create_index(op.f("ix_file_user_id"), "file", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_file_user_id"), table_name="file")
    op.drop_index(op.f("ix_file_storage_key"), table_name="file")
    op.drop_index(op.f("ix_file_status"), table_name="file")
    op.drop_index(op.f("ix_file_scope"), table_name="file")
    op.drop_index(op.f("ix_file_message_id"), table_name="file")
    op.drop_index(op.f("ix_file_is_deleted"), table_name="file")
    op.drop_index(op.f("ix_file_id"), table_name="file")
    op.drop_index(op.f("ix_file_category"), table_name="file")
    op.drop_table("file")
    # ### end Alembic commands ###
