"""add_is_published

Revision ID: 345d4e5e7ec4
Revises: e424a1dcd40e
Create Date: 2025-11-06 20:35:16.447516

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "345d4e5e7ec4"
down_revision: Union[str, Sequence[str], None] = "e424a1dcd40e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("graphagent", sa.Column("is_published", sa.Boolean(), nullable=False, server_default="false"))
    op.create_index(op.f("ix_graphagent_is_published"), "graphagent", ["is_published"], unique=False)
    op.alter_column(
        "provider",
        "provider_config",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "provider",
        "provider_config",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.drop_index(op.f("ix_graphagent_is_published"), table_name="graphagent")
    op.drop_column("graphagent", "is_published")
    # ### end Alembic commands ###
