"""add knowledge set

Revision ID: 36ab2d81f127
Revises: d00feda08541
Create Date: 2025-12-19 21:36:58.456587

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "36ab2d81f127"
down_revision: Union[str, Sequence[str], None] = "d00feda08541"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fileknowledgesetlink",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("file_id", sa.Uuid(), nullable=False),
        sa.Column("knowledge_set_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_fileknowledgesetlink_file_id"), "fileknowledgesetlink", ["file_id"], unique=False)
    op.create_index(op.f("ix_fileknowledgesetlink_id"), "fileknowledgesetlink", ["id"], unique=False)
    op.create_index(
        op.f("ix_fileknowledgesetlink_knowledge_set_id"), "fileknowledgesetlink", ["knowledge_set_id"], unique=False
    )
    op.create_table(
        "knowledgeset",
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_knowledgeset_id"), "knowledgeset", ["id"], unique=False)
    op.create_index(op.f("ix_knowledgeset_is_deleted"), "knowledgeset", ["is_deleted"], unique=False)
    op.create_index(op.f("ix_knowledgeset_user_id"), "knowledgeset", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_knowledgeset_user_id"), table_name="knowledgeset")
    op.drop_index(op.f("ix_knowledgeset_is_deleted"), table_name="knowledgeset")
    op.drop_index(op.f("ix_knowledgeset_id"), table_name="knowledgeset")
    op.drop_table("knowledgeset")
    op.drop_index(op.f("ix_fileknowledgesetlink_knowledge_set_id"), table_name="fileknowledgesetlink")
    op.drop_index(op.f("ix_fileknowledgesetlink_id"), table_name="fileknowledgesetlink")
    op.drop_index(op.f("ix_fileknowledgesetlink_file_id"), table_name="fileknowledgesetlink")
    op.drop_table("fileknowledgesetlink")
    # ### end Alembic commands ###
