"""add_agent_marketplace_and_snapshot_tables

Revision ID: 3d5e4ae2bc9b
Revises: 504ca3e34a8c
Create Date: 2025-12-19 23:02:31.669197

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "3d5e4ae2bc9b"
down_revision: Union[str, Sequence[str], None] = "504ca3e34a8c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agentlike",
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("marketplace_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("user_id", "marketplace_id"),
    )
    op.create_index(op.f("ix_agentlike_marketplace_id"), "agentlike", ["marketplace_id"], unique=False)
    op.create_index(op.f("ix_agentlike_user_id"), "agentlike", ["user_id"], unique=False)
    op.create_table(
        "agentmarketplace",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("agent_id", sa.Uuid(), nullable=False),
        sa.Column("active_snapshot_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("avatar", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("tags", sa.JSON(), nullable=True),
        sa.Column("likes_count", sa.Integer(), nullable=False),
        sa.Column("forks_count", sa.Integer(), nullable=False),
        sa.Column("views_count", sa.Integer(), nullable=False),
        sa.Column("is_published", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("first_published_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_agentmarketplace_active_snapshot_id"), "agentmarketplace", ["active_snapshot_id"], unique=False
    )
    op.create_index(op.f("ix_agentmarketplace_agent_id"), "agentmarketplace", ["agent_id"], unique=False)
    op.create_index(op.f("ix_agentmarketplace_forks_count"), "agentmarketplace", ["forks_count"], unique=False)
    op.create_index(op.f("ix_agentmarketplace_id"), "agentmarketplace", ["id"], unique=False)
    op.create_index(op.f("ix_agentmarketplace_is_published"), "agentmarketplace", ["is_published"], unique=False)
    op.create_index(op.f("ix_agentmarketplace_likes_count"), "agentmarketplace", ["likes_count"], unique=False)
    op.create_index(op.f("ix_agentmarketplace_name"), "agentmarketplace", ["name"], unique=False)
    op.create_index(op.f("ix_agentmarketplace_user_id"), "agentmarketplace", ["user_id"], unique=False)
    op.create_table(
        "agentsnapshot",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("agent_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("configuration", sa.JSON(), nullable=True),
        sa.Column("mcp_server_configs", sa.JSON(), nullable=True),
        sa.Column("knowledge_set_config", sa.JSON(), nullable=True),
        sa.Column("commit_message", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_agentsnapshot_agent_id"), "agentsnapshot", ["agent_id"], unique=False)
    op.create_index(op.f("ix_agentsnapshot_id"), "agentsnapshot", ["id"], unique=False)
    op.add_column("agent", sa.Column("original_source_id", sa.Uuid(), nullable=True))
    op.create_index(op.f("ix_agent_original_source_id"), "agent", ["original_source_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_agent_original_source_id"), table_name="agent")
    op.drop_column("agent", "original_source_id")
    op.drop_index(op.f("ix_agentsnapshot_id"), table_name="agentsnapshot")
    op.drop_index(op.f("ix_agentsnapshot_agent_id"), table_name="agentsnapshot")
    op.drop_table("agentsnapshot")
    op.drop_index(op.f("ix_agentmarketplace_user_id"), table_name="agentmarketplace")
    op.drop_index(op.f("ix_agentmarketplace_name"), table_name="agentmarketplace")
    op.drop_index(op.f("ix_agentmarketplace_likes_count"), table_name="agentmarketplace")
    op.drop_index(op.f("ix_agentmarketplace_is_published"), table_name="agentmarketplace")
    op.drop_index(op.f("ix_agentmarketplace_id"), table_name="agentmarketplace")
    op.drop_index(op.f("ix_agentmarketplace_forks_count"), table_name="agentmarketplace")
    op.drop_index(op.f("ix_agentmarketplace_agent_id"), table_name="agentmarketplace")
    op.drop_index(op.f("ix_agentmarketplace_active_snapshot_id"), table_name="agentmarketplace")
    op.drop_table("agentmarketplace")
    op.drop_index(op.f("ix_agentlike_user_id"), table_name="agentlike")
    op.drop_index(op.f("ix_agentlike_marketplace_id"), table_name="agentlike")
    op.drop_table("agentlike")
    # ### end Alembic commands ###
