"""link agent to knowledge base

Revision ID: 504ca3e34a8c
Revises: 36ab2d81f127
Create Date: 2025-12-19 21:57:08.691335

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "504ca3e34a8c"
down_revision: Union[str, Sequence[str], None] = "36ab2d81f127"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("agent", sa.Column("knowledge_set_id", sa.Uuid(), nullable=True))
    op.create_index(op.f("ix_agent_knowledge_set_id"), "agent", ["knowledge_set_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_agent_knowledge_set_id"), table_name="agent")
    op.drop_column("agent", "knowledge_set_id")
    # ### end Alembic commands ###
