"""add provider_type and is_default to provider table

Revision ID: 5319e6d0a614
Revises: 9919d1058000
Create Date: 2025-10-18 16:55:55.396562

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5319e6d0a614"
down_revision: Union[str, Sequence[str], None] = "9919d1058000"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("provider", sa.Column("provider_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column("provider", sa.Column("is_default", sa.Boolean(), nullable=False))
    op.create_index(op.f("ix_provider_provider_type"), "provider", ["provider_type"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_provider_provider_type"), table_name="provider")
    op.drop_column("provider", "is_default")
    op.drop_column("provider", "provider_type")
    # ### end Alembic commands ###
