"""add category to mcpserver

Revision ID: 69dab3a4473b
Revises: afdbe2e6fb9a
Create Date: 2025-12-13 17:03:17.334810

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "69dab3a4473b"
down_revision: Union[str, Sequence[str], None] = "afdbe2e6fb9a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create SessionMcpServerLink table
    op.create_table(
        "sessionmcpserverlink",
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("mcp_server_id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("session_id", "mcp_server_id"),
    )
    op.create_index(
        op.f("ix_sessionmcpserverlink_mcp_server_id"), "sessionmcpserverlink", ["mcp_server_id"], unique=False
    )
    op.create_index(op.f("ix_sessionmcpserverlink_session_id"), "sessionmcpserverlink", ["session_id"], unique=False)

    # Create enum type for MCP server category
    mcp_category_enum = sa.Enum("SEARCH", "CAPABILITY", "KNOWLEDGE", "INTEGRATION", "GENERAL", name="mcpservercategory")
    mcp_category_enum.create(op.get_bind(), checkfirst=True)

    # Add category column as nullable first
    op.add_column("mcpserver", sa.Column("category", mcp_category_enum, nullable=True))

    # Backfill existing data - default all existing servers to "CAPABILITY" category
    # (they are likely agent-level tool servers)
    connection = op.get_bind()
    connection.execute(sa.text("UPDATE mcpserver SET category = 'CAPABILITY' WHERE category IS NULL"))

    # Make column non-nullable
    op.alter_column("mcpserver", "category", nullable=False)

    # Create index on category for efficient filtering
    op.create_index(op.f("ix_mcpserver_category"), "mcpserver", ["category"], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_mcpserver_category"), table_name="mcpserver")
    op.drop_column("mcpserver", "category")
    op.drop_index(op.f("ix_sessionmcpserverlink_session_id"), table_name="sessionmcpserverlink")
    op.drop_index(op.f("ix_sessionmcpserverlink_mcp_server_id"), table_name="sessionmcpserverlink")
    op.drop_table("sessionmcpserverlink")
    # ### end Alembic commands ###
