"""Add check-in system for daily rewards

Revision ID: 70ee7fb4d40b
Revises: 86191253b794
Create Date: 2025-12-27 15:00:24.027449

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "70ee7fb4d40b"
down_revision: Union[str, Sequence[str], None] = "86191253b794"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "check_ins",
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("check_in_date", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("consecutive_days", sa.Integer(), nullable=False),
        sa.Column("points_awarded", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_user_date", "check_ins", ["user_id", "check_in_date"], unique=True)
    op.create_index(op.f("ix_check_ins_id"), "check_ins", ["id"], unique=False)
    op.create_index(op.f("ix_check_ins_user_id"), "check_ins", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_check_ins_user_id"), table_name="check_ins")
    op.drop_index(op.f("ix_check_ins_id"), table_name="check_ins")
    op.drop_index("idx_user_date", table_name="check_ins")
    op.drop_table("check_ins")
    # ### end Alembic commands ###
