"""remove category

Revision ID: 791bfece478d
Revises: d687a9c06519
Create Date: 2025-12-13 21:37:19.862397

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "791bfece478d"
down_revision: Union[str, Sequence[str], None] = "d687a9c06519"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_mcpserver_category"), table_name="mcpserver")
    op.drop_column("mcpserver", "category")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "mcpserver",
        sa.Column(
            "category",
            postgresql.ENUM("SEARCH", "CAPABILITY", "KNOWLEDGE", "INTEGRATION", "GENERAL", name="mcpservercategory"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.create_index(op.f("ix_mcpserver_category"), "mcpserver", ["category"], unique=False)
    # ### end Alembic commands ###
