"""add_source_version_to_agent

Revision ID: 86191253b794
Revises: d1cead7be3f7
Create Date: 2025-12-22 23:05:27.750745

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "86191253b794"
down_revision: Union[str, Sequence[str], None] = "d1cead7be3f7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("agent", sa.Column("source_version", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("agent", "source_version")
    # ### end Alembic commands ###
