"""add provider and model to session

Revision ID: 8f78abb0fa0c
Revises: 3afab9b3be0e
Create Date: 2025-12-10 16:32:55.747110

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8f78abb0fa0c"
down_revision: Union[str, Sequence[str], None] = "3afab9b3be0e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("session", sa.Column("provider_id", sa.Uuid(), nullable=True))
    op.add_column("session", sa.Column("model", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("session", "model")
    op.drop_column("session", "provider_id")
    # ### end Alembic commands ###
