"""Add user_id to tool, tool_version, and tool_function tables

Revision ID: 9919d1058000
Revises: 522a1aee3f00
Create Date: 2025-10-04 17:35:37.173846

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9919d1058000"
down_revision: Union[str, Sequence[str], None] = "522a1aee3f00"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tool", sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_index(op.f("ix_tool_user_id"), "tool", ["user_id"], unique=False)
    op.add_column("toolfunction", sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_index(op.f("ix_toolfunction_user_id"), "toolfunction", ["user_id"], unique=False)
    op.add_column("toolversion", sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_index(op.f("ix_toolversion_user_id"), "toolversion", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_toolversion_user_id"), table_name="toolversion")
    op.drop_column("toolversion", "user_id")
    op.drop_index(op.f("ix_toolfunction_user_id"), table_name="toolfunction")
    op.drop_column("toolfunction", "user_id")
    op.drop_index(op.f("ix_tool_user_id"), table_name="tool")
    op.drop_column("tool", "user_id")
    # ### end Alembic commands ###
