"""add_graph_config

Revision ID: a05b7d38a4a0
Revises: a7b3c8e51f92
Create Date: 2026-01-07 22:29:03.211631

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a05b7d38a4a0"
down_revision: Union[str, Sequence[str], None] = "a7b3c8e51f92"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("agent", sa.Column("graph_config", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("agent", "graph_config")
    # ### end Alembic commands ###
