"""add require_tool_confirmation to agent

Revision ID: a857da5c3a97
Revises: 82dbf3c6846c
Create Date: 2025-09-23 19:15:25.967979

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a857da5c3a97"
down_revision: Union[str, Sequence[str], None] = "82dbf3c6846c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "agent", sa.Column("require_tool_confirmation", sa.Boolean(), nullable=False, server_default=sa.false())
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("agent", "require_tool_confirmation")
    # ### end Alembic commands ###
