"""add_tier_to_session

Revision ID: ab49b572f009
Revises: f0d7b93430e1
Create Date: 2026-01-12 20:55:07.656593

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ab49b572f009"
down_revision: Union[str, Sequence[str], None] = "f0d7b93430e1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create enum type first (PostgreSQL requires explicit creation)
    modeltier_enum = sa.Enum("ULTRA", "PRO", "STANDARD", "LITE", name="modeltier")
    modeltier_enum.create(op.get_bind(), checkfirst=True)

    op.add_column("session", sa.Column("model_tier", modeltier_enum, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("session", "model_tier")
    # Drop the enum type (PostgreSQL requires explicit cleanup)
    op.execute("DROP TYPE IF EXISTS modeltier")
    # ### end Alembic commands ###
