"""add token for consume

Revision ID: afdbe2e6fb9a
Revises: 2f7e4f948ed0
Create Date: 2025-12-13 12:03:46.877054

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "afdbe2e6fb9a"
down_revision: Union[str, Sequence[str], None] = "2f7e4f948ed0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("consumerecord", sa.Column("input_tokens", sa.Integer(), nullable=True))
    op.add_column("consumerecord", sa.Column("output_tokens", sa.Integer(), nullable=True))
    op.add_column("consumerecord", sa.Column("total_tokens", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("consumerecord", "total_tokens")
    op.drop_column("consumerecord", "output_tokens")
    op.drop_column("consumerecord", "input_tokens")
    # ### end Alembic commands ###
