"""add_is_official

Revision ID: c3ccad954d9b
Revises: 345d4e5e7ec4
Create Date: 2025-11-06 21:18:42.246531

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c3ccad954d9b"
down_revision: Union[str, Sequence[str], None] = "345d4e5e7ec4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("graphagent", sa.Column("is_official", sa.Boolean(), nullable=False, server_default="false"))
    op.create_index(op.f("ix_graphagent_is_official"), "graphagent", ["is_official"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_graphagent_is_official"), table_name="graphagent")
    op.drop_column("graphagent", "is_official")
    # ### end Alembic commands ###
