"""add_tier_pricing_to_consume

Revision ID: c712246c7034
Revises: ab49b572f009
Create Date: 2026-01-14 20:45:35.088242

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "c712246c7034"
down_revision: Union[str, Sequence[str], None] = "ab49b572f009"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("consumerecord", sa.Column("model_tier", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column("consumerecord", sa.Column("tier_rate", sa.Float(), nullable=True))
    op.add_column(
        "consumerecord", sa.Column("calculation_breakdown", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("consumerecord", "calculation_breakdown")
    op.drop_column("consumerecord", "tier_rate")
    op.drop_column("consumerecord", "model_tier")
    # ### end Alembic commands ###
