"""add folder

Revision ID: d00feda08541
Revises: 791bfece478d
Create Date: 2025-12-15 20:29:42.039689

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "d00feda08541"
down_revision: Union[str, Sequence[str], None] = "791bfece478d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "folder",
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_folder_id"), "folder", ["id"], unique=False)
    op.create_index(op.f("ix_folder_is_deleted"), "folder", ["is_deleted"], unique=False)
    op.create_index(op.f("ix_folder_parent_id"), "folder", ["parent_id"], unique=False)
    op.create_index(op.f("ix_folder_user_id"), "folder", ["user_id"], unique=False)
    op.add_column("file", sa.Column("folder_id", sa.Uuid(), nullable=True))
    op.create_index(op.f("ix_file_folder_id"), "file", ["folder_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_file_folder_id"), table_name="file")
    op.drop_column("file", "folder_id")
    op.drop_index(op.f("ix_folder_user_id"), table_name="folder")
    op.drop_index(op.f("ix_folder_parent_id"), table_name="folder")
    op.drop_index(op.f("ix_folder_is_deleted"), table_name="folder")
    op.drop_index(op.f("ix_folder_id"), table_name="folder")
    op.drop_table("folder")
    # ### end Alembic commands ###
