"""Add readme to agent_marketplace

Revision ID: d1cead7be3f7
Revises: 3d5e4ae2bc9b
Create Date: 2025-12-22 21:53:05.805997

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "d1cead7be3f7"
down_revision: Union[str, Sequence[str], None] = "3d5e4ae2bc9b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("agentmarketplace", sa.Column("readme", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("agentmarketplace", "readme")
    # ### end Alembic commands ###
