"""Migrate provider

Revision ID: d594146a15c1
Revises: 0a40031876f0
Create Date: 2025-11-26 16:17:34.444979

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d594146a15c1"
down_revision: Union[str, Sequence[str], None] = "0a40031876f0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    provider_scope_enum = sa.Enum("system", "user", "org", name="providerscope")
    provider_type_enum = sa.Enum("openai", "azure_openai", "google", "google_vertex", name="providertype")

    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        provider_scope_enum.create(bind, checkfirst=True)
        provider_type_enum.create(bind, checkfirst=True)
    op.add_column("provider", sa.Column("scope", provider_scope_enum, nullable=True))
    op.execute("UPDATE provider SET scope = 'system' WHERE is_system = true")
    op.execute("UPDATE provider SET scope = 'user' WHERE is_system = false")
    op.execute("UPDATE provider SET scope = 'user' WHERE scope IS NULL")
    op.alter_column("provider", "scope", nullable=False)

    op.alter_column("provider", "user_id", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column(
        "provider",
        "provider_type",
        existing_type=sa.VARCHAR(),
        type_=provider_type_enum,
        existing_nullable=False,
        postgresql_using="provider_type::providertype",
    )
    op.drop_index(op.f("ix_provider_is_system"), table_name="provider")
    op.create_index(op.f("ix_provider_scope"), "provider", ["scope"], unique=False)
    op.create_unique_constraint("unique_provider_per_scope", "provider", ["provider_type", "scope", "user_id"])
    op.drop_column("provider", "is_system")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("provider", sa.Column("is_system", sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.execute("UPDATE provider SET is_system = true WHERE scope = 'system'")
    op.execute("UPDATE provider SET is_system = false WHERE scope != 'system'")
    op.alter_column("provider", "is_system", nullable=False)
    op.drop_constraint("unique_provider_per_scope", "provider", type_="unique")
    op.drop_index(op.f("ix_provider_scope"), table_name="provider")
    op.create_index(op.f("ix_provider_is_system"), "provider", ["is_system"], unique=False)
    op.alter_column(
        "provider",
        "provider_type",
        existing_type=sa.Enum("openai", "azure_openai", "google", "google_vertex", name="providertype"),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    op.execute("UPDATE provider SET user_id = 'da2a8078-dd7c-4052-ad68-1209c3f647f1' WHERE user_id IS NULL")
    op.alter_column("provider", "user_id", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_column("provider", "scope")
    # ### end Alembic commands ###
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        op.execute("DROP TYPE IF EXISTS providerscope")
        op.execute("DROP TYPE IF EXISTS providertype")
