"""add citation

Revision ID: d687a9c06519
Revises: 06220fc6f1ff
Create Date: 2025-12-13 21:00:59.381372

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "d687a9c06519"
down_revision: Union[str, Sequence[str], None] = "06220fc6f1ff"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "citation",
        sa.Column("message_id", sa.Uuid(), nullable=False),
        sa.Column("url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("cited_text", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("start_index", sa.Integer(), nullable=True),
        sa.Column("end_index", sa.Integer(), nullable=True),
        sa.Column("search_queries", sa.JSON(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_citation_id"), "citation", ["id"], unique=False)
    op.create_index(op.f("ix_citation_message_id"), "citation", ["message_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_citation_message_id"), table_name="citation")
    op.drop_index(op.f("ix_citation_id"), table_name="citation")
    op.drop_table("citation")
    # ### end Alembic commands ###
