"""add redemption

Revision ID: de3ff879f68e
Revises: d594146a15c1
Create Date: 2025-12-03 17:53:28.309406

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "de3ff879f68e"
down_revision: Union[str, Sequence[str], None] = "d594146a15c1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "redemptioncode",
        sa.Column("code", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("max_usage", sa.Integer(), nullable=False),
        sa.Column("current_usage", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("expires_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_redemptioncode_code"), "redemptioncode", ["code"], unique=True)
    op.create_index(op.f("ix_redemptioncode_id"), "redemptioncode", ["id"], unique=False)
    op.create_index(op.f("ix_redemptioncode_is_active"), "redemptioncode", ["is_active"], unique=False)
    op.create_table(
        "redemptionhistory",
        sa.Column("code_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("redeemed_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_redemptionhistory_code_id"), "redemptionhistory", ["code_id"], unique=False)
    op.create_index(op.f("ix_redemptionhistory_id"), "redemptionhistory", ["id"], unique=False)
    op.create_index(op.f("ix_redemptionhistory_user_id"), "redemptionhistory", ["user_id"], unique=False)
    op.create_table(
        "userwallet",
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("virtual_balance", sa.BigInteger(), nullable=False),
        sa.Column("total_credited", sa.BigInteger(), nullable=False),
        sa.Column("total_consumed", sa.BigInteger(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_userwallet_id"), "userwallet", ["id"], unique=False)
    op.create_index(op.f("ix_userwallet_user_id"), "userwallet", ["user_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_userwallet_user_id"), table_name="userwallet")
    op.drop_index(op.f("ix_userwallet_id"), table_name="userwallet")
    op.drop_table("userwallet")
    op.drop_index(op.f("ix_redemptionhistory_user_id"), table_name="redemptionhistory")
    op.drop_index(op.f("ix_redemptionhistory_id"), table_name="redemptionhistory")
    op.drop_index(op.f("ix_redemptionhistory_code_id"), table_name="redemptionhistory")
    op.drop_table("redemptionhistory")
    op.drop_index(op.f("ix_redemptioncode_is_active"), table_name="redemptioncode")
    op.drop_index(op.f("ix_redemptioncode_id"), table_name="redemptioncode")
    op.drop_index(op.f("ix_redemptioncode_code"), table_name="redemptioncode")
    op.drop_table("redemptioncode")
    # ### end Alembic commands ###
