"""update_agent_db

Revision ID: e424a1dcd40e
Revises: cfde435d9dde
Create Date: 2025-11-01 00:09:07.761941

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e424a1dcd40e"
down_revision: Union[str, Sequence[str], None] = "cfde435d9dde"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "graphagent",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
        sa.Column("state_schema", sa.JSON(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("parent_agent_id", sa.Uuid(), nullable=True),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_graphagent_id"), "graphagent", ["id"], unique=False)
    op.create_index(op.f("ix_graphagent_parent_agent_id"), "graphagent", ["parent_agent_id"], unique=False)
    op.create_index(op.f("ix_graphagent_user_id"), "graphagent", ["user_id"], unique=False)
    op.create_table(
        "graphedge",
        sa.Column("from_node_id", sa.Uuid(), nullable=False),
        sa.Column("to_node_id", sa.Uuid(), nullable=False),
        sa.Column("condition", sa.JSON(), nullable=True),
        sa.Column("graph_agent_id", sa.Uuid(), nullable=False),
        sa.Column("label", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_graphedge_from_node_id"), "graphedge", ["from_node_id"], unique=False)
    op.create_index(op.f("ix_graphedge_graph_agent_id"), "graphedge", ["graph_agent_id"], unique=False)
    op.create_index(op.f("ix_graphedge_id"), "graphedge", ["id"], unique=False)
    op.create_index(op.f("ix_graphedge_to_node_id"), "graphedge", ["to_node_id"], unique=False)
    op.create_table(
        "graphnode",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column("node_type", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("config", sa.JSON(), nullable=True),
        sa.Column("graph_agent_id", sa.Uuid(), nullable=False),
        sa.Column("position_x", sa.Float(), nullable=True),
        sa.Column("position_y", sa.Float(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_graphnode_graph_agent_id"), "graphnode", ["graph_agent_id"], unique=False)
    op.create_index(op.f("ix_graphnode_id"), "graphnode", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_graphnode_id"), table_name="graphnode")
    op.drop_index(op.f("ix_graphnode_graph_agent_id"), table_name="graphnode")
    op.drop_table("graphnode")
    op.drop_index(op.f("ix_graphedge_to_node_id"), table_name="graphedge")
    op.drop_index(op.f("ix_graphedge_id"), table_name="graphedge")
    op.drop_index(op.f("ix_graphedge_graph_agent_id"), table_name="graphedge")
    op.drop_index(op.f("ix_graphedge_from_node_id"), table_name="graphedge")
    op.drop_table("graphedge")
    op.drop_index(op.f("ix_graphagent_user_id"), table_name="graphagent")
    op.drop_index(op.f("ix_graphagent_parent_agent_id"), table_name="graphagent")
    op.drop_index(op.f("ix_graphagent_id"), table_name="graphagent")
    op.drop_table("graphagent")
    # ### end Alembic commands ###
