"""add session status

Revision ID: e427ec7ce799
Revises: 16fcd09524ba
Create Date: 2026-01-15 00:51:11.625488

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "e427ec7ce799"
down_revision: Union[str, Sequence[str], None] = "16fcd09524ba"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
