"""add knowledge_set_id to sessions

Revision ID: e9c929c46d85
Revises: f649991a610e
Create Date: 2026-01-16 00:41:15.764125

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e9c929c46d85"
down_revision: Union[str, Sequence[str], None] = "f649991a610e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("session", sa.Column("knowledge_set_id", sa.Uuid(), nullable=True))
    op.create_index(op.f("ix_session_knowledge_set_id"), "session", ["knowledge_set_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_session_knowledge_set_id"), table_name="session")
    op.drop_column("session", "knowledge_set_id")
    # ### end Alembic commands ###
