"""add_agent_metadata

Revision ID: f0d7b93430e1
Revises: a05b7d38a4a0
Create Date: 2026-01-07 23:26:44.557183

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f0d7b93430e1"
down_revision: Union[str, Sequence[str], None] = "a05b7d38a4a0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("message", sa.Column("agent_metadata", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("message", "agent_metadata")
    # ### end Alembic commands ###
