"""add consume tables with auto increment biz_no

Revision ID: f2a66d835d66
Revises: fd17b4979d60
Create Date: 2025-10-21 21:38:24.370133

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f2a66d835d66"
down_revision: Union[str, Sequence[str], None] = "fd17b4979d60"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "consume_records",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("biz_no", sa.Integer(), autoincrement=True, nullable=True),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("auth_provider", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("sku_id", sa.Integer(), nullable=True),
        sa.Column("scene", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("session_id", sa.Uuid(), nullable=True),
        sa.Column("topic_id", sa.Uuid(), nullable=True),
        sa.Column("message_id", sa.Uuid(), nullable=True),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("consume_state", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("remote_error", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("remote_response", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_consume_records_auth_provider"), "consume_records", ["auth_provider"], unique=False)
    op.create_index(op.f("ix_consume_records_biz_no"), "consume_records", ["biz_no"], unique=True)
    op.create_index(op.f("ix_consume_records_id"), "consume_records", ["id"], unique=False)
    op.create_index(op.f("ix_consume_records_user_id"), "consume_records", ["user_id"], unique=False)
    op.create_table(
        "user_consume_summaries",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("auth_provider", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("total_amount", sa.BigInteger(), nullable=False),
        sa.Column("total_count", sa.Integer(), nullable=False),
        sa.Column("success_count", sa.Integer(), nullable=False),
        sa.Column("failed_count", sa.Integer(), nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_consume_summaries_auth_provider"), "user_consume_summaries", ["auth_provider"], unique=False
    )
    op.create_index(op.f("ix_user_consume_summaries_id"), "user_consume_summaries", ["id"], unique=False)
    op.create_index(op.f("ix_user_consume_summaries_user_id"), "user_consume_summaries", ["user_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_consume_summaries_user_id"), table_name="user_consume_summaries")
    op.drop_index(op.f("ix_user_consume_summaries_id"), table_name="user_consume_summaries")
    op.drop_index(op.f("ix_user_consume_summaries_auth_provider"), table_name="user_consume_summaries")
    op.drop_table("user_consume_summaries")
    op.drop_index(op.f("ix_consume_records_user_id"), table_name="consume_records")
    op.drop_index(op.f("ix_consume_records_id"), table_name="consume_records")
    op.drop_index(op.f("ix_consume_records_biz_no"), table_name="consume_records")
    op.drop_index(op.f("ix_consume_records_auth_provider"), table_name="consume_records")
    op.drop_table("consume_records")
    # ### end Alembic commands ###
