"""Add agent_run table

Revision ID: f5e0d3529c12
Revises: e9c929c46d85
Create Date: 2026-01-16 17:54:22.699361

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "f5e0d3529c12"
down_revision: Union[str, Sequence[str], None] = "e9c929c46d85"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agentrun",
        sa.Column("message_id", sa.Uuid(), nullable=False),
        sa.Column("execution_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("agent_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("agent_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("agent_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("started_at", sa.Float(), nullable=False),
        sa.Column("ended_at", sa.Float(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("node_data", sa.JSON(), nullable=True),
        sa.Column("error_type", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("error_message", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_agentrun_execution_id"), "agentrun", ["execution_id"], unique=False)
    op.create_index(op.f("ix_agentrun_id"), "agentrun", ["id"], unique=False)
    op.create_index(op.f("ix_agentrun_message_id"), "agentrun", ["message_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_agentrun_message_id"), table_name="agentrun")
    op.drop_index(op.f("ix_agentrun_id"), table_name="agentrun")
    op.drop_index(op.f("ix_agentrun_execution_id"), table_name="agentrun")
    op.drop_table("agentrun")
    # ### end Alembic commands ###
