"""remove google_search_enabled from sessions

Revision ID: f649991a610e
Revises: efa73edfbb15
Create Date: 2026-01-15 23:21:10.619965

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f649991a610e"
down_revision: Union[str, Sequence[str], None] = "efa73edfbb15"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("session", "google_search_enabled")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "session",
        sa.Column(
            "google_search_enabled", sa.BOOLEAN(), server_default=sa.text("false"), autoincrement=False, nullable=False
        ),
    )
    # ### end Alembic commands ###
